package gui;

public enum StartMode {

    FREE_DRAWING,
    LOAD_CONFIGURATION_FOR_EDIT,
    PERFORM_INTERVIEW,
    LOAD_PROJECT,
    LOAD_CONFIGURATION,
    UPDATE,
    CREATE_QUESTIONAIRE,
    EDIT_TEMPLATE
}
